[package]
name = "danieluntask/signal"
description = "Simple and usefully signal module."
version = "0.1.7"
license = "MIT"
authors = ["DanielUnTask"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Task = "danieluntask/task@0.1.1"